### ISSUE TITLE
请问何时可以开源？

### ISSUE THREAD

**Issue by awfniewf** [GANWANSHUI/ES6D#1]
首先恭喜大佬的成果被CVPR2022接收，拜读过您的论文，很佩服您的想法，想问您何时能够开源？

**Comment by GANWANSHUI** [comment]
您好，

感谢关注，最近一直在忙其他的事情，抱歉！

我这个星期先把网络模型和那几个数据集的GP发上去。


Best,

wanshui




awfniewf ***@***.***> 于2022年6月6日周一 12:08写道：

**Comment by awfniewf** [comment]
谢谢您的回复！如果这周能发的话真是太好了，非常感谢您！
