### ISSUE TITLE
关于ES6D在LineMOD数据集上的应用

### ISSUE THREAD

**Issue by awfniewf** [GANWANSHUI/ES6D#12]
作者您好，我在知网上看到ES6D的论文中也在LineMOD数据集上也进行了测试，请问是否可以放在教程中呢？谢谢您。

**Comment by GANWANSHUI** [comment]
您好，那个实验是我们比较久之前跑得了，代码也没有整理，有需要得话，可以加我微信交流：15521072307

**Comment by awfniewf** [comment]
好的，谢谢！
