### ISSUE TITLE
请问是否方便提供以ADD(S)为loss的ES6D在T-less数据集训练而成的模型？

### ISSUE THREAD

**Issue by awfniewf** [GANWANSHUI/ES6D#14]
作者您好。由于densefusion，PVN3D,FFB6D等算法均以传统的ADD(S)为损失函数，因此用同样以ADD(S)为损失函数的ES6D与其进行比较更能体现出本网络结构的特点。谢谢！

**Comment by GANWANSHUI** [comment]
开源的时候我们没有重新使用ADD(S)训练了。需要在ES6D上使用ADD(S)训练的话，把--loss_type 换成ADD就可以训练了。一些定量的比较的话，可以参考论文正文的Table1(T-LESS)，和补充材料的Table 1（YCB）

**Comment by awfniewf** [comment]
> 开源的时候我们没有重新使用ADD(S)训练了。需要在ES6D上使用ADD(S)训练的话，把--loss_type 换成ADD就可以训练了。一些定量的比较的话，可以参考论文正文的Table1(T-LESS)，和补充材料的Table 1（YCB）

好的，谢谢您。
