### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './datasets/tless/test_primesense_gt_mask_mat.txt'

### ISSUE THREAD

**Issue by Jsvi53** [GANWANSHUI/ES6D#15]
作者你好！按照readme操作的时候，成功执行完python ./datasets/tless/tless_preparation.py --tless_path ./datasets/tless --train_set False但是并没有test_primesense_gt_mask_mat和test_primesense_gt_mask_mat.txt，这是什么原因?

**Comment by GANWANSHUI** [comment]
路径有没设置对呢，可以先调试一下看看
