### ISSUE TITLE
Continuous symmetry object

### ISSUE THREAD

**Issue by Jsvi53** [GANWANSHUI/ES6D#18]
Can your model handle objects with continuous symmetries (such as textured cylinders) and how well does it perform on them?

**Comment by GANWANSHUI** [comment]
![1678458261641](https://user-images.githubusercontent.com/43164272/224340549-dd6cbb4e-a40e-4ab8-9dd6-888ab2b2a326.png)

From Figure 5 in the main paper, we can see that the proposed metric and loss could handle the continuous symmetries you mentioned.
