### ISSUE TITLE
关于训练数据中训练物体个数的问题。

### ISSUE THREAD

**Issue by awfniewf** [GANWANSHUI/ES6D#5]
您好，在作者您给出的train_pbr( https://bop.felk.cvut.cz/media/data/bop_datasets/tless_train_pbr.zip.) 
中，其训练物体数量为50，而作者您的模型是按照30个训练物体训练而成的，请问我该如何判断这50个训练物体中哪30个是作者您所要求或需要的？不好意思，我对目前的tless数据集格式不太了解。

**Comment by GANWANSHUI** [comment]
您好，可以参考train_pbr/000000/scene_gt.json文件里边的obj_id, 似乎最大的id是30，可以再确认一下。

**Comment by awfniewf** [comment]
> 您好，可以参考train_pbr/000000/scene_gt.json文件里边的obj_id, 似乎最大的id是30，可以再确认一下。

感谢您的回答，我看到obj_id了。我发现不同于其他的tless数据集，这些数据集里每个编号文件夹中的obj_id是一致的。而train_pbr中每个编号文件夹中的obj_id是打乱的。我再研究一下，谢谢。

**Comment by neverstoplearn** [comment]
> 您好，在作者您给出的train_pbr( https://bop.felk.cvut.cz/media/data/bop_datasets/tless_train_pbr.zip.) 中，其训练物体数量为50，而作者您的模型是按照30个训练物体训练而成的，请问我该如何判断这50个训练物体中哪30个是作者您所要求或需要的？不好意思，我对目前的tless数据集格式不太了解。

作者您好，数据下载链接失效了，是否可以提供新的下载链接，谢谢。
