### ISSUE TITLE
关于预训练的问题

### ISSUE THREAD

**Issue by awfniewf** [GANWANSHUI/ES6D#8]
请问作者您的特征提取网络resnet18与pointnet在进行tless数据集或YCB数据集训练前是否进行了其余数据集比如imagenet1K数据集之类的预训练？
我对这方面知识还不是很了解，希望能得到您的解答，谢谢。

**Comment by GANWANSHUI** [comment]
您好，我们稍微修改了resnet18和pointnet，所有的训练都没有用预训练模型。

**Comment by awfniewf** [comment]
> 您好，我们稍微修改了resnet18和pointnet，所有的训练都没有用预训练模型。

感谢您的回答！

**Comment by awfniewf** [comment]
> 您好，我们稍微修改了resnet18和pointnet，所有的训练都没有用预训练模型。

不好意思，我还有一个问题。倘若resnet18是经过imagnet预训练过后，再进行tless数据集训练的话(即ES6D中使用resnet18预训练模型，然后再进行tless的训练)，训练时间或者准确度会有怎样的变化？请问您的团队是否尝试过。谢谢！

**Comment by GANWANSHUI** [comment]
我们没有尝试过。使用相关的预训练模型可能会有帮助，可以先看看其他的6D姿态估计的文章有没使用预训练。

**Comment by awfniewf** [comment]
> 我们没有尝试过。使用相关的预训练模型可能会有帮助，可以先看看其他的6D姿态估计的文章有没使用预训练。

好的，谢谢！
