### ISSUE TITLE
Meaning of symmetry_ids

### ISSUE THREAD

**Issue by Jianqiuer** [GANWANSHUI/ES6D#9]
https://github.com/GANWANSHUI/ES6D/blob/595347d3902336fef2f8e89269f4dbc4b45e1bfb/tools/grouped_primitives_tools/grouped_primitives_constructor.py#L68

Thanks for your work. I am not sure what the meaning of symmetry_ids is.  Why select the first ten objects ranger than the former commented out symmetry_ids?

**Comment by GANWANSHUI** [comment]
A little mistake. Just use the commented one is OK.  We will update it later.

**Comment by moningkai** [comment]
@Jianqiuer We have corrected the mistake.
https://github.com/GANWANSHUI/ES6D/commit/08ab9abb92a7ef49a113f1e14813428f2c60ead9

**Comment by Jianqiuer** [comment]
Thanks, @moningkai @GANWANSHUI
